-- Tạo bảng LOP
CREATE TABLE LOP (
    MaLop CHAR(7) PRIMARY KEY,
    TenLop NVARCHAR(50) NOT NULL,
    SiSo TINYINT CHECK (SiSo > 0) NOT NULL
);

-- Tạo bảng MONHOC
CREATE TABLE MONHOC (
    MaMH CHAR(6) PRIMARY KEY,
    TenMH NVARCHAR(50) NOT NULL,
    TCTL TINYINT CHECK (TCTL > 0) NOT NULL,
    TCTH TINYINT CHECK (TCTH >= 0) NOT NULL
);

-- Tạo bảng SINHVIEN
CREATE TABLE SINHVIEN (
    MSSV CHAR(6) PRIMARY KEY,
    HoTen NVARCHAR(50) NOT NULL,
    NTNS DATE NOT NULL,
    Phai BIT DEFAULT 1 CHECK (Phai IN (0,1)),
    MaLop CHAR(7) NOT NULL,
    FOREIGN KEY (MaLop) REFERENCES LOP(MaLop) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Tạo bảng DIEMSV
CREATE TABLE DIEMSV (
    MSSV CHAR(6),
    MaMH CHAR(6),
    Diem DECIMAL(3,1) CHECK (Diem IS NULL OR (Diem >= 0 AND Diem <= 10)),
    PRIMARY KEY (MSSV, MaMH),
    FOREIGN KEY (MSSV) REFERENCES SINHVIEN(MSSV) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (MaMH) REFERENCES MONHOC(MaMH) ON DELETE CASCADE ON UPDATE CASCADE
);
